// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlZ8pKx7kCaCCMWCXEgkZLSbSuA2u7a0A',
    appId: '1:27541201097:web:67e989bbcb036fe143ad18',
    messagingSenderId: '27541201097',
    projectId: 'parcial-04',
    authDomain: 'parcial-04.firebaseapp.com',
    storageBucket: 'parcial-04.appspot.com',
    measurementId: 'G-22P6MVGCVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzb39zaLKKNJV9RMu7ecpO6NI0_0peUgU',
    appId: '1:27541201097:android:afacac96c2c8f55543ad18',
    messagingSenderId: '27541201097',
    projectId: 'parcial-04',
    storageBucket: 'parcial-04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmlVC7QqHXZBK2aNN-STqgGXCmj5kSWdo',
    appId: '1:27541201097:ios:90d8d4d9e9a6352a43ad18',
    messagingSenderId: '27541201097',
    projectId: 'parcial-04',
    storageBucket: 'parcial-04.appspot.com',
    iosClientId: '27541201097-mgov9f8a2fucrikp9of3n65jl7jo5ncn.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial4Electiva3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmlVC7QqHXZBK2aNN-STqgGXCmj5kSWdo',
    appId: '1:27541201097:ios:90d8d4d9e9a6352a43ad18',
    messagingSenderId: '27541201097',
    projectId: 'parcial-04',
    storageBucket: 'parcial-04.appspot.com',
    iosClientId: '27541201097-mgov9f8a2fucrikp9of3n65jl7jo5ncn.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial4Electiva3',
  );
}
